import React from "react";

export const metadata = {
  title: "About - Cahaya Mercusuar Indonesia",
  description: "Generated by create next app",
};

const About = () => {
  return <div>About</div>;
};

export default About;
