import Info from "@/components/contact/info";
import Mail from "@/components/contact/mail";
import Image from "next/image";
import React from "react";

export const metadata = {
  title: "Contact - Cahaya Mercusuar Indonesia",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <>
      <section className="relative">
        <Image
          src="/images/bg/bbblurry.svg"
          alt=""
          width={1920}
          height={1080}
          className="fixed -z-50"
        />
        <>
          <Mail />
          <Info />
        </>
      </section>
    </>
  );
};

export default Contact;
